[global]
   workgroup = WORKGROUP
   server string = Camera File Share
   security = user
   map to guest = bad user
   guest account = nobody

[FileShare]
   comment = Shared Files
   path = /home/pi/shared
   guest ok = yes
   writable = yes
   browseable = yes
   create mask = 0666
   directory mask = 0777
